Regex and test for credit card numbers
NCATComp410/comp410_summer_2022 pull request #84
Opened 2022-07-12 01:23 UTC by alexisc0305

Develop regex and test to detect credit card numbers.
Closes #83

2022-07-12 09:29 UTC, claesmk requested changes
See commend on handling dashes in credit card numbers.  Also note that [0-9] could be simplified with \d

2022-07-12 23:53 UTC, alexisc0305 commented on test_team2.py
> +        ccn = '3333 333333 33333' # American Express
Thank you for your feedback!

2022-07-13 00:52 UTC, scary-monsters approved these changes
Awesome. Nice job.

2022-07-13 00:53 UTC, scary-monsters approved these changes

2022-07-13 00:53 UTC, Drdj11 reviewed
clean regex

2022-07-13 00:54 UTC, jscedeno reviewed
looks good

2022-07-13 01:59 UTC, claesmk approved these changes
Looks good

2022-07-13 01:59 UTC, merged